version: "3.7"
services:
  fetch-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    restart: unless-stopped
    ports:
      - "8080:8080"
